name: iris
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - pandas
  - requests
  - tqdm
  - openai
  - accelerate
  - transformers